---
- name: Upload the health binary to the Raspberry Pi
  copy:
    src: "{{ local_bin_path }}"
    dest: "{{ working_dir }}/health"
    owner: "{{ filesystem.user }}"
    group: "{{ filesystem.group }}"
    mode: '0755'
